### PR TITLE
Support cross-region disaster recovery

### PR DESCRIPTION
**Pull request by jglick**
Extends #29 to support restoring persistent volumes to a cluster in another region, essentially a quick-and-dirty AWS implementation of https://github.com/vmware-tanzu/velero/issues/103. Main changes relative to #29:
* copies EBS snapshots to an alternate region when so configured
* adjusts region, not just AZ, node affinity metadata when restoring

Tested with Velero 1.6.3 against `v1.21.2-eks-0389ca3` in basic usage (backing up and restoring a few stateful sets with disks of ~50Gb each from `us-east-1` to `us-west-1`). Still TBD how practical this feature is under more realistic load, but filing as draft in case anyone is interested.

### CODE REVIEW

**Comment by jglick** [comment]
> We have a different architecture in the work for handling cross region mobility

Is there anything I can watch for details, and possibly contributing testing or patches?

**Comment by jglick** [comment]
Note that there have been commits to this branch after the PR was closed, which GitHub does not display: https://github.com/vmware-tanzu/velero-plugin-for-aws/compare/main...jglick:x-region

**Comment by jglick** [comment]
Likely to have merge conflicts with #93, not yet evaluated.

**Comment by SCLogo** [comment]
@jglick for temp solution will you open PR, or do we need to fork and commit your changes?

**Comment by jglick** [comment]
@SCLogo https://github.com/vmware-tanzu/velero-plugin-for-aws/pull/90#issuecomment-946232600 so I will not be reopening this. If you want to try using it anyway, https://github.com/vmware-tanzu/velero-plugin-for-aws/pull/90#issuecomment-957963959

**Comment by Shapai** [comment]
Hey @jglick,thanks for this feature. we would like to use your version of cross region restore, how can we use your version of plugin while installing velero 
for example while doing a velero install , what should be the entry for --plugins flag ?
ex

```
velero install \
    --provider aws \
    --plugins velero/velero-plugin-for-aws:v1.4.0 \
    --bucket velerobkp \
    --backup-location-config region=us-east-2 \
    --snapshot-location-config region=us-east-2 \
    --secret-file secret-file
```

what should be for **--plugins**

**Comment by jglick** [comment]
@Shapai this is not currently published as an image, so you would need to build it from sources, push to your own registry, and use that. To be practical for more than a couple of volumes, you would also need to build Velero core from sources in https://github.com/vmware-tanzu/velero/pull/4242. To repeat previous warnings, this patch is completely unsupported, and has not been brought up to date with subsequent official changes to the AWS/EBS plugin (same for the core patch). _Very roughly_ the process would look like

```bash
account=$(aws sts get-caller-identity | jq -r .Account)
for region in us-east-1 us-west-1
do
	registry=$account.dkr.ecr.$region.amazonaws.com
	if [ $region = us-east-1 ]
	then
		zone=us-east-1a
		alt_region=us-west-1
	else
		zone=us-west-1b
		alt_region=us-east-1
	fi
	cluster_name=eks-$region
	aws ecr create-repository --repository-name testing/velero --region $region || echo already exists
	aws ecr create-repository --repository-name testing/velero-plugin-for-aws --region $region || echo already exists
	make -C /path/to/patched/velero REGISTRY=$registry/testing VERSION=testing container
	docker build -t $registry/testing/velero-plugin-for-aws /path/to/patched/velero-plugin-for-aws
	aws ecr get-login-password --region $region | docker login --username AWS --password-stdin $registry
	docker push $registry/testing/velero
	docker push $registry/testing/velero-plugin-for-aws
	cat >/tmp/velero.yaml <<YAML
image:
  repository: $registry/testing/velero
initContainers:
- name: velero-plugin-for-aws
  image: $registry/testing/velero-plugin-for-aws
  volumeMounts:
  - mountPath: /target
    name: plugins
configuration:
  provider: aws
  backupStorageLocation:
    bucket: testing
    config:
      region: $alt_region
  volumeSnapshotLocation:
    config:
      region: $region
      altRegion: $alt_region
  extraEnvVars:
    AWS_CLUSTER_NAME: $cluster_name
    VELERO_AWS_AZ_OVERRIDE: $zone
serviceAccount:
  server:
    create: false
    name: velero
credentials:
  useSecret: false
YAML
	kubectl config set-context --current --cluster $cluster_name
	helm install velero vmware-tanzu/velero --version 2.24.0 --namespace velero --create-namespace -f /tmp/velero.yaml
done
```

**Comment by Shapai** [comment]
Hey @jglick , Thanks for your inputs and steps that are provided, I was able to create backup and restore it . the snapshots were copied to other regions and then restored using snapshots. There is one issue that i am facing now the pods are still in pending state. 

 ```
kubectl get pods -n zookeeper
NAME          READY   STATUS    RESTARTS   AGE
zookeeper-0   0/2     Pending   0          9m29s
zookeeper-1   0/2     Pending   0          9m29s
zookeeper-2   0/2     Pending   0          9m29s
zookeeper-3   0/2     Pending   0          9m29s
zookeeper-4   0/2     Pending   0          9m29s
zookeeper-5   0/2     Pending   0          9m29s
```

reason being 
```
0/1 nodes are available: 1 node(s) had volume node affinity conflict
```

looks like the pv still has labels of us-east-2 the source cluster whereas it should be of us-west-2

```
 kubectl describe pv pvc-261b9803-8e55-4880-bb31-b29ca3a6c323
Name:              pvc-261b9803-8e55-4880-bb31-b29ca3a6c323
**Labels:            failure-domain.beta.kubernetes.io/region=us-east-2
                   failure-domain.beta.kubernetes.io/zone=us-west-2a**
                   velero.io/backup-name=zookeeper-x
                   velero.io/restore-name=zookeeper-x-20220406130317
```

How can we make sure when the restore happens it has the region set to us-west-2 and not us-east-2 , due to this it goes in pending and complains of node affinity conflict

**Comment by jglick** [comment]
Currently this patch supports `failure-domain.beta.kubernetes.io/zone` but not `failure-domain.beta.kubernetes.io/region`. I do not really recall but I suspect if you are using a newer cluster the volumes would be labeled with `topology.kubernetes.io/zone` and `topology.kubernetes.io/region` which are supported. Adding support for `failure-domain.beta.kubernetes.io/region` would probably be straightforward, it was just not required for the environment I was testing in. https://github.com/vmware-tanzu/velero-plugin-for-aws/blob/b1519bf6a0a25fa653e6b02aa9af53d812adf0ea/velero-plugin-for-aws/restoreplugin.go#L34-L36 https://github.com/vmware-tanzu/velero-plugin-for-aws/blob/b1519bf6a0a25fa653e6b02aa9af53d812adf0ea/velero-plugin-for-aws/restoreplugin.go#L79-L87 https://github.com/vmware-tanzu/velero-plugin-for-aws/blob/b1519bf6a0a25fa653e6b02aa9af53d812adf0ea/velero-plugin-for-aws/restoreplugin.go#L112-L119

**Comment by jglick** [comment]
```console
$ COSIGN_EXPERIMENTAL=1 cosign verify ghcr.io/jglick/velero-plugin-for-aws:x-region

Verification for ghcr.io/jglick/velero-plugin-for-aws:x-region --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - Existence of the claims in the transparency log was verified offline
  - Any certificates were verified against the Fulcio roots.

[{"critical":{"identity":{"docker-reference":"ghcr.io/jglick/velero-plugin-for-aws"},"image":{"docker-manifest-digest":"sha256:41726206fedc18846d82003ef9869620438e48770f043c0dd9a3b872233177db"},…
```

**Comment by shashankpai** [comment]
Is there any chance this can be reopened and raised, so velero backup and restore in cross region can be possible. This worked well for us.

**Pull request closed without merging**
