### PR TITLE
remove redundant non-AWS-specific BSL/VSL documentation

### PR DESCRIPTION
**Pull request by skriss**
Signed-off-by: Steve Kriss <krisss@vmware.com>

PR 2 of 4 for https://github.com/vmware-tanzu/velero/issues/2003 -- also see https://github.com/vmware-tanzu/velero/pull/2046 for related changes in the main velero repo.

Once we're happy with this, I'll make similar changes for the Azure and GCP repos.

cc @carlisia @nrb @prydonius

### CODE REVIEW

**Comment by skriss** [comment]
Hmm. It's definitely in the `velero install` commands in the README, but I agree it's not on this page.

An alternative I thought about is rather than doing a table to document all the config options, put an example BSL/VSL YAML with all the different options shown and commented.

**Comment by carlisia** [comment]
I really like that. I was going to say that I like having the yaml example that was deleted, but the tradeoff is having to update it (it = all the 3 plugins) when things change. But this doesn't even change that frequently now that I think about it.

**Comment by skriss** [comment]
See latest commit for a WIP example of documenting using example YAML - WDYT? Should I do this instead of the table?

**Comment by carlisia** [comment]
Yes, this is perfect! 

One suggestion to make things more clear. On the paragraph below, where it starts:
`The AWS plugin supports` maybe change it to something like `Here are all parameters the AWS plugin supports`. This way it doesn't seem so much that it's a different thing.

**Comment by skriss** [comment]
OK, I fully switched to YAML for the BSL doc. WDYT? Should I proceed with the other docs like this as well?

**Comment by carlisia** [comment]
Oh I love this format! Imo, much better.

**Comment by skriss** [comment]
:+1: I like it as well. I switched the VSL doc over too - I'll wait for any feedback from @nrb/@prydonius before moving on to GCP/Azure though :)

**Pull request merged**
