### PR TITLE
update AWS-SDK-GO to >= version 1.29.11

### PR DESCRIPTION
**Pull request by jones-paul1525**
Update the version of the Amazon AWS SDK that the plugin is using to a version that has support for connecting to regional STS endpoints - and by extension, private VPC STS endpoints, to authenticate using Amazon's recommended method - IAM Roles for Service Accounts. This will allow EKS clusters that do not have access to the internet to run Velero and configure it to use the private VPC STS endpoint for authentication.

### CODE REVIEW

**Comment by skriss** [comment]
Thanks for the PR @jones-paul1525! This looks fine to me. Were you able to test this change by any chance?

**Comment by jones-paul1525** [comment]
> Were you able to test this change by any chance?

Other than basic tests to make sure it still builds, I have not been able to test.  I will see if it is a possibility for me to test this change within my organization's development sandbox.  Thank you!

**Comment by skriss** [comment]
:+1: if anyone else has the bandwidth to help out with a quick smoke test on this, that'd be great. cc @nrb @carlisia @ashish-amarnath

**Comment by ashish-amarnath** [comment]
Can do this sometime today or tomorrow.

**Comment by ashish-amarnath** [comment]
I was able to verify the object store plugin. To verify the volumesnapshotter plugin I need more time to verify the volumesnapshotting.

**Comment by skriss** [comment]
I think if it compiles and the object store works fine, then we're probably OK.

**Comment by ashish-amarnath** [comment]
I am OK with merging this.

**Comment by ashish-amarnath** [comment]
Thanks for you PR @jones-paul1525

**Pull request merged**
